---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/accounts":
    get:
      summary: Retrieves all accounts
      tags:
      - Accounts
      responses:
        '200':
          description: account found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
        '404':
          description: account not found
        '406':
          description: unsupported accept header
    post:
      summary: Creates an account
      tags:
      - Accounts
      parameters: []
      responses:
        '201':
          description: account created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                account_type_id:
                  type: integer
                name:
                  type: string
                account_alias:
                  type: string
                cbu:
                  type: string
                description:
                  type: text
                balance:
                  type: decimal
              required:
              - user_id
              - account_type_id
              - name
              - balance
  "/accounts/id":
    get:
      summary: Retrieves a account
      tags:
      - Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: account found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
        '404':
          description: account not found
        '406':
          description: unsupported accept header
    patch:
      summary: Updates an account
      tags:
      - Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: account found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
        '404':
          description: account not found
        '406':
          description: unsupported accept header
    delete:
      summary: Delete an account
      tags:
      - Accounts
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: account found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
        '404':
          description: account not found
        '406':
          description: unsupported accept header
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
