default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: yuen_api_development
  username: yuen_api
  password: '12345678'

test:
  <<: *default
  database: yuen_api_test
  username: yuen_api
  password: '12345678'

production:
  <<: *default
  database: yuen_api_production
  username: yuen_api
  password: <%= ENV['YUEN_API_DATABASE_PASSWORD'] %>
