default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: self_administer_api_development
  username: self_administer_api
  password: '12345678'

test:
  <<: *default
  database: self_administer_api_test
  username: self_administer_api
  password: '12345678'

production:
  <<: *default
  database: self_administer_api_production
  username: self_administer_api
  password: <%= ENV['SELF_ADMINISTER_API_DATABASE_PASSWORD'] %>
